"""Generate a short data-quality report from the processed dataset.

Run with:  python -m src.quality_report   (after python -m src.build_dataset)

Writes reports/data_quality.md with row counts per season, all distinct
status values, and automated checks for gaps and oddities.
"""

import pandas as pd

from src.config import QUALITY_REPORT_MD, REPORTS_DIR, RESULTS_PARQUET


def season_table(df: pd.DataFrame) -> pd.DataFrame:
    per_season = df.groupby("season").agg(
        races=("round", "nunique"),
        rows=("driver_id", "size"),
        drivers=("driver_id", "nunique"),
    )
    per_season["rows_per_race"] = (per_season["rows"] / per_season["races"]).round(1)
    return per_season


def status_table(df: pd.DataFrame) -> pd.DataFrame:
    counts = df["status"].value_counts()
    return pd.DataFrame({
        "count": counts,
        "share": (counts / len(df) * 100).round(2).astype(str) + "%",
    })


def find_oddities(df: pd.DataFrame) -> list[str]:
    notes = []

    nulls = df.isna().sum()
    for col, n in nulls[nulls > 0].items():
        notes.append(f"`{col}` has {n:,} missing values.")

    dupes = df.duplicated(subset=["season", "round", "driver_id"]).sum()
    if dupes:
        notes.append(f"{dupes} duplicate (season, round, driver) rows — needs investigation.")
    else:
        notes.append("No duplicate (season, round, driver) rows: each driver appears once per race.")

    # A round sequence with holes would mean a race is missing entirely.
    for season, g in df.groupby("season"):
        rounds = sorted(g["round"].unique())
        expected = list(range(1, max(rounds) + 1))
        if rounds != expected:
            missing = sorted(set(expected) - set(rounds))
            notes.append(f"Season {season}: missing round(s) {missing}.")

    grid_zero = (df["grid"] == 0).sum()
    if grid_zero:
        notes.append(
            f"`grid` is 0 in {grid_zero:,} rows. In the Ergast schema grid 0 means "
            "the driver started from the pit lane (not a data error)."
        )

    no_code = df.loc[df["driver_code"].isna(), "driver_id"].nunique()
    if no_code:
        notes.append(
            f"{no_code} drivers have no three-letter `driver_code` (mostly pre-2003 "
            "drivers, before the FIA introduced permanent codes)."
        )

    zero_laps = (df["laps"] == 0).sum()
    if zero_laps:
        notes.append(
            f"{zero_laps:,} rows have `laps` = 0: the driver was classified in the "
            "race but never completed a lap (first-corner crashes, formation-lap "
            "failures, withdrawals)."
        )

    return notes


def build_report(df: pd.DataFrame) -> str:
    lines = [
        "# Data quality report — race results 2000–2024",
        "",
        "Auto-generated by `python -m src.quality_report`. "
        f"Dataset: `data/processed/results.parquet`, {len(df):,} rows, "
        f"{df['season'].nunique()} seasons.",
        "",
        "## Rows per season",
        "",
        season_table(df).to_markdown(),
        "",
        "## Distinct status values",
        "",
        f"{df['status'].nunique()} distinct values. Counts over the whole dataset:",
        "",
        status_table(df).to_markdown(),
        "",
        "## Gaps and oddities",
        "",
    ]
    lines += [f"- {note}" for note in find_oddities(df)]
    lines.append("")
    return "\n".join(lines)


def main():
    df = pd.read_parquet(RESULTS_PARQUET)
    report = build_report(df)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    QUALITY_REPORT_MD.write_text(report, encoding="utf-8")
    print(f"Wrote {QUALITY_REPORT_MD}")


if __name__ == "__main__":
    main()
